ARG VERSION=latest
ARG REPO=ghcr.io/vnvlabs

FROM ${REPO}/simple:${VERSION} as simple
FROM ${REPO}/heat:${VERSION} as heat

COPY --from=simple ${SOFTWARE_DIR}/simple ${SOFTWARE_DIR}/simple
COPY --from=simple /home/user/.vnv /home/user/.vnvtmp
RUN cd ${HOME} && awk '!seen[$0]++' .vnv .vnvtmp > .vnvt && mv .vnvt .vnv && rm .vnvtmp


COPY demo_config /config
RUN cat /config/vnv.registration >> ${HOME}.vnv
