
ARG VERSION=latest
ARG REPO=ghcr.io/vnvlabs

FROM ${REPO}/asgard:${VERSION} as asgard
FROM ${REPO}/heat:${VERSION} as heat
FROM ${REPO}/mfem:${VERSION} as mfem 
FROM ${REPO}/miniamr:${VERSION} as miniamr
FROM ${REPO}/simple:${VERSION} as simple
FROM ${REPO}/swfft:${VERSION} as swfft
FROM ${REPO}/xsbench:${VERSION} as xsbench
FROM ${REPO}/moose:${VERSION} as moose

COPY --from=simple ${SOFTWARE_DIR}/simple ${SOFTWARE_DIR}/simple
COPY --from=heat ${SOFTWARE_DIR}/heat ${SOFTWARE_DIR}/heat
COPY --from=asgard ${SOFTWARE_DIR}/asgard ${SOFTWARE_DIR}/asgard
COPY --from=mfem ${SOFTWARE_DIR}/mfem ${SOFTWARE_DIR}/mfem
COPY --from=miniamr ${SOFTWARE_DIR}/miniAMR ${SOFTWARE_DIR}/miniAMR
COPY --from=swfft ${SOFTWARE_DIR}/swfft ${SOFTWARE_DIR}/swfft
COPY --from=xsbench ${SOFTWARE_DIR}/xs-bench ${SOFTWARE_DIR}/xs-bench

ENV VNV_CONFIG=${VNV_CONFIG}:${SOFTWARE_DIR}/simple/gui/vnv.__registration__ 
ENV VNV_CONFIG=${VNV_CONFIG}:${SOFTWARE_DIR}/heat/gui/vnv.__registration__ 
ENV VNV_CONFIG=${VNV_CONFIG}:${SOFTWARE_DIR}/asgard/vnv/config/vnv.__registration__ 
ENV VNV_CONFIG=${VNV_CONFIG}:${SOFTWARE_DIR}/mfem/gui/vnv.__registration__ 
ENV VNV_CONFIG=${VNV_CONFIG}:${SOFTWARE_DIR}/miniAMR/vnv/gui/vnv.__registration__ 
ENV VNV_CONFIG=${VNV_CONFIG}:${SOFTWARE_DIR}/swfft/vnv/gui/vnv.__registration__ 
ENV VNV_CONFIG=${VNV_CONFIG}:${SOFTWARE_DIR}/xs-bench/vnv/gui/vnv.__registration__ 

COPY all_config /config
ENV VNV_CONFIG=${VNV_CONFIG}:/config/vnv.registration
