ARG VERSION=latest
ARG REPO=ghcr.io/vnvlabs


FROM ${REPO}/swfft:${VERSION} as swfft
FROM ${REPO}/miniamr:${VERSION} as miniamr
FROM ${REPO}/xsbench:${VERSION} as xsbench

COPY --from=miniamr ${SOFTWARE_DIR}/miniAMR ${SOFTWARE_DIR}/miniAMR
COPY --from=swfft ${SOFTWARE_DIR}/swfft ${SOFTWARE_DIR}/swfft
ENV VNV_CONFIG=${VNV_CONFIG}:${SOFTWARE_DIR}/swfft/vnv/gui/vnv.__registration__ 
ENV VNV_CONFIG=${VNV_CONFIG}:${SOFTWARE_DIR}/miniAMR/vnv/gui/vnv.__registration__ 

COPY proxy_config /config
ENV VNV_CONFIG=${VNV_CONFIG}:/config/vnv.registration

