ARG VERSION=latest
FROM vnv_simple:${VERSION} as simple
FROM vnv_heat:${VERSION} as heat

COPY --from=simple ${SOURCE_DIR}/simple ${SOURCE_DIR}/simple
ENV VNV_CONFIG=${VNV_CONFIG}:${SOURCE_DIR}/simple/build/vnv.__registration__:

COPY demo_config /config
ENV VNV_CONFIG=${VNV_CONFIG}:/config/vnv.__registration__

