
ARG VERSION=latest
ARG REPO=ghcr.io/vnvlabs

FROM ${REPO}/asgard:${VERSION} as asgard

FROM ${REPO}/heat:${VERSION} as heat

FROM ${REPO}/mfem:${VERSION} as mfem 

FROM ${REPO}/miniamr:${VERSION} as miniamr

FROM ${REPO}/simple:${VERSION} as simple

FROM ${REPO}/swfft:${VERSION} as swfft

FROM ${REPO}/xsbench:${VERSION} as xsbench

# Moose has vnv-hypre-petsc-libmesh-moose all installed already. 
FROM ${REPO}/moose:${VERSION} as moose

COPY --from=simple ${SOFTWARE_DIR}/simple ${SOFTWARE_DIR}/simple
COPY --from=simple /home/user/.vnv /home/user/.vnvtmp
RUN cd ${HOME} && awk '!seen[$0]++' .vnv .vnvtmp > .vnvt && mv .vnvt .vnv && rm .vnvtmp

COPY --from=heat ${SOFTWARE_DIR}/heat ${SOFTWARE_DIR}/heat
COPY --from=heat /home/user/.vnv /home/user/.vnvtmp
RUN cd ${HOME} && awk '!seen[$0]++' .vnv .vnvtmp > .vnvt && mv .vnvt .vnv && rm .vnvtmp

COPY --from=asgard ${SOFTWARE_DIR}/asgard ${SOFTWARE_DIR}/asgard
COPY --from=asgard /home/user/.vnv /home/user/.vnvtmp
RUN cd ${HOME} && awk '!seen[$0]++' .vnv .vnvtmp > .vnvt && mv .vnvt .vnv && rm .vnvtmp
COPY --from=mfem ${SOFTWARE_DIR}/mfem ${SOFTWARE_DIR}/mfem
COPY --from=mfem /home/user/.vnv /home/user/.vnvtmp
RUN cd ${HOME} && awk '!seen[$0]++' .vnv .vnvtmp > .vnvt && mv .vnvt .vnv && rm .vnvtmp

COPY --from=miniamr ${SOFTWARE_DIR}/miniAMR ${SOFTWARE_DIR}/miniAMR
COPY --from=miniamr /home/user/.vnv /home/user/.vnvtmp
RUN cd ${HOME} && awk '!seen[$0]++' .vnv .vnvtmp > .vnvt && mv .vnvt .vnv && rm .vnvtmp

COPY --from=swfft ${SOFTWARE_DIR}/swfft ${SOFTWARE_DIR}/swfft
COPY --from=swfft /home/user/.vnv /home/user/.vnvtmp
RUN cd ${HOME} && awk '!seen[$0]++' .vnv .vnvtmp > .vnvt && mv .vnvt .vnv && rm .vnvtmp

COPY --from=xsbench ${SOFTWARE_DIR}/xs-bench ${SOFTWARE_DIR}/xs-bench
COPY --from=xsbench /home/user/.vnv /home/user/.vnvtmp
RUN cd ${HOME} && awk '!seen[$0]++' .vnv .vnvtmp > .vnvt && mv .vnvt .vnv && rm .vnvtmp

COPY all_config /config
RUN cat /config/vnv.registration >> ${HOME}.vnv
