

ARG FROM_IMAGE=ubuntu:20.04
ARG GUI_IMAGE=ghcr.io/vnvlabs/gui:nightly
ARG PLUGIN_IMAGE=ghcr.io/vnvlabs/plugins:nightly

FROM ${GUI_IMAGE}

FROM ${PLUGIN_IMAGE}

FROM ${FROM_IMAGE}

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=America/New_York
ENV THEIA_DEFAULT_PLUGINS=local-dir:/vnvgui/theia/plugins
ENV PARAVIEW_DIR=/vnvgui/paraview 
ENV PVPYTHON=${PARAVIEW_DIR}/bin/pvpython 
ENV PATH=/vnvgui/node/bin/:$PATH 
ENV DOWNLOAD_PARAVIEW=1
ENV SOFTWARE_DIR=/home/user/software

COPY --from=0 /vnvgui/node /vnvgui/node
COPY --from=0 /vnvgui/theia /vnvgui/theia
COPY --from=0 /vnvgui/gui /vnvgui/gui
COPY --from=0 /vnvgui/paraview /vnvgui/paraview 


LABEL VNV_GUI_EQUIPT=1
WORKDIR /vnvgui/gui
ENTRYPOINT ["./launch.sh"] 
