# This is a basic workflow to help you get started with Actions

name: Nightly Build and Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
           submodules: recursive
           fetch-depth: 0
      - name: Get new commits
        run: echo "NEW_COMMIT_COUNT=$(git log --oneline --since '24 hours ago' | wc -l)" >> $GITHUB_ENV
      - name: Build And Release
        if: ${{ env.NEW_COMMIT_COUNT > 0 }}
        run: ./docker.sh nightly
               

