# This is a basic workflow to help you get started with Actions

name: Nightly Build and Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

jobs:
  env:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: ./.github/actions/stage
        with:
            stage: env
  gui:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: ./.github/actions/stage
        with:
            stage: gui
  vnv:
    runs-on: ubuntu-latest
    needs : [gui]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: ./.github/actions/stage
        with:
            stage: vnv
  performance:
    runs-on: ubuntu-latest
    needs : [vnv]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: ./.github/actions/stage
        with:
            stage: performance
  
            
            


  


               

